[pki.root]
cert_path = "root.cert"
key_path = "root.key"
depth = 2
password = "swordfish"

[pki.root.identity]
locality_name = "Drancy"
common_name = "My Register"
country_name = "FR"
email_address = "my-register@example.com"
organization_name = "My Register"

[pki.intermediate]
cert_path = "intermediate.cert"
key_path = "intermediate.key"
issuer = "root"
password = "password"
depth = 1

[pki.intermediate.identity]
locality_name = "Magnat L'Etrange"
common_name = "CertiFarm"
country_name = "FR"
email_address = "app@example.com"
organization_name = "CertiFarm"
